### ISSUE TITLE
Refresh cache

### ISSUE THREAD

**Issue by cholcombe973** [FauxFaux/apt-pkg-native-rs#1]
How would one go about refreshing the package cache after an outside call to apt-get update is performed?  I'm calling this right after an apt-get update but it doesn't seem to be picking up the new package version: https://github.com/cholcombe973/skynet/blob/master/src/apt.rs#L141

**Comment by FauxFaux** [comment]
I've added a way to drop and re-create the cache: a `reload()` method.

Could you please test it against `git` before I release it? I don't quite have the motivation to run some tests in a vm/container.

```toml
[dependencies]
apt-pkg-native = { git = "https://github.com/FauxFaux/apt-pkg-native-rs" }
```

At the same time, I've changed the way the synchronisation works internally: There's now an actual `Mutex`, which will intentionally deadlock any code which is trying to be smart with `Cache`s. Don't get caught out by that.
